export const products = [
  {
    product_id: "1",
    product_name: "Sampalok",
    price: 115,
    unit: "kg",
    farm_name: "Harvest Haven Farm",
    image: "/products/sampalok.png",
    category: "Fruits",
  },
  {
    product_id: "2",
    product_name: "Corn",
    price: 250,
    unit: "kg",
    farm_name: "Kamalig Farm",
    image: "/products/corn.png",
    category: "Vegetables",
  },
  {
    product_id: "3",
    product_name: "Eggplant",
    price: 120,
    unit: "kg",
    farm_name: "Conchie Farm",
    image: "/products/eggplant.png",
    category: "Vegetables",
  },
  {
    product_id: "4",
    product_name: "Cabbage",
    price: 180,
    unit: "kg",
    farm_name: "ForThee Farm",
    image: "/products/cabbage.png",
    category: "Vegetables",
  },
  {
    product_id: "5",
    product_name: "Mushrooms",
    price: 110,
    unit: "kg",
    farm_name: "Dinakdakan Farm",
    image: "/products/mushrooms.png",
    category: "Vegetables",
  },
  {
    product_id: "6",
    product_name: "Bell Peppers",
    price: 220,
    unit: "kg",
    farm_name: "Baliwag Farm",
    image: "/products/bell-peppers.png",
    category: "Vegetables",
  },
  {
    product_id: "7",
    product_name: "Cucumbers",
    price: 120,
    unit: "kg",
    farm_name: "Sinawali Farm",
    image: "/products/cucumbers.png",
    category: "Vegetables",
  },
  {
    product_id: "8",
    product_name: "Tomatoes",
    price: 100,
    unit: "kg",
    farm_name: "Pinked Farm",
    image: "/products/tomatoes.png",
    category: "Vegetables",
  },
  {
    product_id: "9",
    product_name: "Strawberries",
    price: 325,
    unit: "kg",
    farm_name: "Baguio Farm",
    image: "/products/strawberries.png",
    category: "Fruits",
  },
];

export const farms = [
  {
    farm_id: "1",
    farm_name: "Harvest Haven Farm",
    image: "/farms/farm-1.png",
    location: "Gatgatan",
  },
  {
    farm_id: "2",
    farm_name: "Kamalig Farm",
    image: "/farms/farm-2.png",
    location: "Tarlac",
  },
  {
    farm_id: "3",
    farm_name: "Conchie Farm",
    image: "/farms/farm-3.png",
    location: "Pampanga",
  },
  {
    farm_id: "4",
    farm_name: "ForThee Farm",
    image: "/farms/farm-4.png",
    location: "Nueva Ecija",
  },
  {
    farm_id: "5",
    farm_name: "Dinakdakan Farm",
    image: "/farms/farm-5.png",
    location: "Bulacan",
  },
  {
    farm_id: "6",
    farm_name: "Baliwag Farm",
    image: "/farms/farm-6.png",
    location: "Bulacan",
  },
  {
    farm_id: "7",
    farm_name: "Sinawali Farm",
    image: "/farms/farm-7.png",
    location: "Bulacan",
  },
  {
    farm_id: "8",
    farm_name: "Pinked Farm",
    image: "/farms/farm-8.png",
    location: "Nueva Ecija",
  },
  {
    farm_id: "9",
    farm_name: "Baguio Farm",
    image: "/farms/farm-9.png",
    location: "Nueva Ecija",
  },
];

export let cart = [
  {
    cart_id: "1",
    product_id: "4",
    quantity: 2,
  },
  {
    cart_id: "2",
    product_id: "1",
    quantity: 3,
  },
];
