import { ProductData } from "@/types";
import { FarmerData } from "@/types";

export const products: ProductData[] = [
  {
    product_id: "1",
    farmer_id: "1",
    product_name: "Sampalok",
    price: 115,
    unit: "kg",
    image: "/products/sampalok.png",
    category: "Fruits",
  },
  {
    product_id: "2",
    farmer_id: "2",
    product_name: "Corn",
    price: 250,
    unit: "kg",
    image: "/products/corn.png",
    category: "Vegetables",
  },
  {
    product_id: "3",
    farmer_id: "3",
    product_name: "Eggplant",
    price: 120,
    unit: "kg",
    image: "/products/eggplant.png",
    category: "Vegetables",
  },
  {
    product_id: "4",
    farmer_id: "4",
    product_name: "Cabbage",
    price: 180,
    unit: "kg",
    image: "/products/cabbage.png",
    category: "Vegetables",
  },
  {
    product_id: "5",
    farmer_id: "5",
    product_name: "Mushrooms",
    price: 110,
    unit: "kg",
    image: "/products/mushrooms.png",
    category: "Vegetables",
  },
  {
    product_id: "6",
    farmer_id: "6",
    product_name: "Bell Peppers",
    price: 220,
    unit: "kg",
    image: "/products/bell-peppers.png",
    category: "Vegetables",
  },
  {
    product_id: "7",
    farmer_id: "7",
    product_name: "Cucumbers",
    price: 120,
    unit: "kg",
    image: "/products/cucumbers.png",
    category: "Vegetables",
  },
  {
    product_id: "8",
    farmer_id: "8",
    product_name: "Tomatoes",
    price: 100,
    unit: "kg",
    image: "/products/tomatoes.png",
    category: "Vegetables",
  },
  {
    product_id: "9",
    farmer_id: "9",
    product_name: "Strawberries",
    price: 325,
    unit: "kg",
    image: "/products/strawberries.png",
    category: "Fruits",
  },
];

export const farmers: FarmerData[] = [
  {
    farmer_id: "1",
    farm_name: "Harvest Haven Farm",
    name: "John Doe",
    image: "/farms/farm-1.png",
    location: "Gatgatan",
  },
  {
    farmer_id: "2",
    farm_name: "Kamalig Farm",
    name: "Jane Smith",
    image: "/farms/farm-2.png",
    location: "Tarlac",
  },
  {
    farmer_id: "3",
    farm_name: "Conchie Farm",
    name: "Alice Johnson",
    image: "/farms/farm-3.png",
    location: "Pampanga",
  },
  {
    farmer_id: "4",
    farm_name: "ForThee Farm",
    name: "Bob Brown",
    image: "/farms/farm-4.png",
    location: "Nueva Ecija",
  },
  {
    farmer_id: "5",
    farm_name: "Dinakdakan Farm",
    name: "Charlie Davis",
    image: "/farms/farm-5.png",
    location: "Bulacan",
  },
  {
    farmer_id: "6",
    farm_name: "Baliwag Farm",
    name: "Emily Wilson",
    image: "/farms/farm-6.png",
    location: "Bulacan",
  },
  {
    farmer_id: "7",
    farm_name: "Sinawali Farm",
    name: "Frank Harris",
    image: "/farms/farm-7.png",
    location: "Bulacan",
  },
  {
    farmer_id: "8",
    farm_name: "Pinked Farm",
    name: "Grace Martin",
    image: "/farms/farm-8.png",
    location: "Nueva Ecija",
  },
  {
    farmer_id: "9",
    farm_name: "Baguio Farm",
    name: "Henry Lee",
    image: "/farms/farm-9.png",
    location: "Nueva Ecija",
  },
];
